name: BUILD, TEST AND DEPLOY - devstageprod

env:
  AZURE_WEBAPP_NAME: bpcalc-csd1    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'                 # set this to the .NET Core version to use

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build
        run: dotnet build --configuration Release
      
      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
   
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unit Tests
        run: dotnet test --configuration Release --logger "trx;LogFileName=test-results.trx" || true
      - name: Unit Tests Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
         name: BP Calculator - Unit Tests
         path: "**/test-results.trx"                            
         reporter: dotnet-trx
         fail-on-error: true
      - name: NDepend
        uses: ndepend/ndepend-action@v1
        with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
         license: ${{ secrets.NDependLicense }}
         stopIfQGFailed: true
     
  e2e_tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
  
  DeployDev:
    name: Deploy to Development environment
    permissions:
      contents: none
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/main'
    needs: [build, test, ]
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }} #'https://bpcalc-csd1-dev.azurewebsites.net'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App - Development
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.BP_CALC_DEV_KEY }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  DeployStaging:
    name: Staging
    permissions:
      contents: none
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/main'
    needs: [e2e_tests, DeployDev]
    environment:
      name: 'Staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }} #https://bpcalc-csd1-staging.azurewebsites.net

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App - Staging
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.BP_CALC_STAGING_KEY }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  
  DeployProd:
    name: Production
    permissions:
      contents: none
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/main'
    needs: [DeployStaging]
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }} #https://bpcalc-csd1.azurewebsites.net

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App - Staging
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.BP_CALC_KEY }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
