name: CI + CD deploy-to-dev

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            
      - name: Build
        run: dotnet build --configuration Release
  
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Unit Tests
        run: dotnet test --configuration Release --logger "trx;LogFileName=test-results.trx" || true

      - name: Unit Tests Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
         name: BP Calculator - Unit Tests
         path: "**/test-results.trx"                            
         reporter: dotnet-trx
         fail-on-error: true
    
  DeployDev:
    name: Deploy to Dev 
    if: github.event_name == 'refs/heads/main'
    needs: [build, test]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'https://bpcalc-csd1.azurewebsites.net'
    steps:
      - name: Deploy
        run: echo I am deploying to development environment! 
